from afxapicom import Client

print("fxapicom - Python Client for fxapi.com")
print("=" * 40)
print()
print("To use this library, initialize the client with your API key:")
print()
print("  import afxapicom")
print("  client = afxapicom.Client('YOUR_API_KEY')")
print()
print("Available methods:")
print("  client.status()                          - Check API status")
print("  client.currencies(currencies=[...])      - List available currencies")
print("  client.latest(base_currency, currencies) - Latest exchange rates")
print("  client.historical(date, ...)             - Historical rates")
print("  client.range(start, end, ...)            - Rate range over time")
print("  client.convert(value, ...)               - Convert currencies")
print()
print("See README.md for full usage examples.")
